use_frameworks!

platform :ios, '10.0'

target 'ZLThemeKit_Example' do
  pod 'ZLThemeKit', :path => '../'

  target 'ZLThemeKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
